### ISSUE TITLE
Password encoding problem

### ISSUE THREAD

**Issue by Yamakaky** [saik0/humblebundle-python#10]
Hi
I have a "wrong password" error. My hib password contains & and -, are you sure your package correctly handles it ?

**Comment by saik0** [comment]
Not able to reproduce in python 2 or 3 with a password containing all of `!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~`. Are you certain you're escaping any `'"\` characters?

See https://docs.python.org/3/reference/lexical_analysis.html#string-and-bytes-literals

**Comment by Yamakaky** [comment]
Sorry, I share my account with a friend and he changed the email address ^^
